---
# defaults file for roles/postgres
container_runtime: "/usr/bin/{{ container_command }}"

postgres_os_user: postgres
postgres_os_group: postgres
postgres_image: "postgres:14"

packages: []

postgres_data_dir: "/var/lib/postgresql"

state: "present"
