---
# Playbook to install Executor
#

- name: Provision Executor
  hosts: "{{ executors_group_name }}:!disabled"
  become: true
  gather_facts: true
  serial: 1
  roles:
    - apimon_executor
  tags: executor
