---
# Playbook to start Globalmon
#
- name: "Starting Globalmon"
  hosts: "{{ globalmon_group_name }}:!disabled"
  become: true
  tasks:
    - name: Start globalmon
      ansible.builtin.service:
        name: "cloudmon-globalmon"
        state: "started"
