---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics-processor
spec:
  rules:
    - host: metrics
      http:
        paths:
          - backend:
              service:
                name: "metrics-processor"
                port:
                  name: "api"
            path: /
            pathType: Prefix
