---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: metrics-processor-config
    literals: []
  - name: metrics-processor-confd
    literals: []

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: base
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: metrics-processor
      app.kubernetes.io/part-of: stackmon
      app.kubernetes.io/version: 1.0.0

resources:
  - service.yaml
  - ingress.yaml
  - deployment.yaml

secretGenerator:
  - name: metrics-processor-secrets
    literals: []
