---
# tasks file for epmon

- name: Include variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ distro_lookup_path }}"
      paths:
        - "vars"

- name: Install required packages
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ item }}"
  loop: 
    - "{{ packages }}"
  when: "ansible_facts.pkg_mgr != 'atomic_container'"
  register: task_result
  until: task_result is success
  retries: 5

- name: Create epmon group
  become: yes
  ansible.builtin.group:
    name: "{{ epmon_os_group }}"
    state: "present"

- name: Create epmon user
  become: true
  ansible.builtin.user:
    name: "{{ epmon_os_user }}"
    group: "{{ epmon_os_group }}"
    groups: "{{ (container_command == 'docker') | ternary('docker', '', omit) }}"
    state: "present"

- name: Write epmon SystemD unit file
  become: true
  ansible.builtin.template:
    src: "epmon.service.j2"
    dest: "{{ epmon_systemd_unit_path }}"
  notify:
    - Restart epmon

- name: Create required directories
  become: true
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    state: "directory"
    owner: "{{ epmon_os_user }}"
    group: "{{ epmon_os_group }}"
    mode: "{{ item.mode | default(omit) }}"
  loop:
    - {dest: "{{ epmon_config_dir }}", mode: "0755"}

- name: Write env
  become: true
  ansible.builtin.template:
    src: "env_epmon"
    dest: "{{ epmon_env_path }}"
    owner: "{{ epmon_os_user }}"
    group: "{{ epmon_os_group }}"
    mode: "0644"
  notify:
    - Restart epmon

- name: Write logging.conf
  become: true
  ansible.builtin.template:
    src: logging.conf
    dest: "{{ epmon_config_dir }}/logging.conf"
    owner: "{{ epmon_os_user }}"
    group: "{{ epmon_os_group }}"
    mode: "0644"
  notify:
    - Restart epmon

- name: Write epmon config
  become: true
  ansible.builtin.copy:
    content: "{{ epmon_config | to_nice_yaml(indent=2, width=79) }}"
    dest: "{{ epmon_config_path }}"
    group: "{{ epmon_os_group }}"
    owner: "{{ epmon_os_user }}"
    mode: "0644"
  when:
    - "epmon_config is defined"
  notify:
    - Restart epmon

- name: Write epmon secure config
  become: true
  ansible.builtin.copy:
    content: "{{ epmon_secure_config | to_nice_yaml(indent=2, width=79) }}"
    dest: "{{ epmon_secure_config_path }}"
    group: "{{ epmon_os_group }}"
    owner: "{{ epmon_os_user }}"
    mode: "0644"
  when:
    - "epmon_secure_config is defined"
  notify:
    - Restart epmon
