---
# handlers file for executor
- name: Restart executor
  become: true
  ansible.builtin.systemd:
    name: "{{ executor_systemd_service_name }}"
    enabled: true
    state: "restarted"
    daemon_reload: true
