---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: "base"
      app.kubernetes.io/managed-by: "kustomize"
      app.kubernetes.io/name: "grafana"
      app.kubernetes.io/version: "1.0.0"

images:
  - name: "grafana/grafana"
    newName: "docker.io/grafana/grafana"
    newTag: "latest"
  - name: "grafana/grafana-image-renderer"
    newName: "docker.io/grafana/grafana"
    newTag: "latest"

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
