---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: sdb-secrets
    literals:
      - SDB_DATABASE_URI=sqlite:///example.sqlite

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: base
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: status-dashboard
      app.kubernetes.io/version: 1.0.0

resources:
  - service.yaml
  - ingress.yaml
  - deployment.yaml
