---
remove_packages:
  - docker.io
  - docker-doc
  - docker-compose
  - podman-docker
  - containerd
  - runc

distro_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

container_command: docker
