---
# tasks file for scheduler

- name: Include variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: "{{ distro_lookup_path }}"
      paths:
        - "vars"

- name: Install required packages
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ item }}"
  loop: 
    - "{{ packages }}"
  when: "ansible_facts.pkg_mgr != 'atomic_container'"
  register: task_result
  until: task_result is success
  retries: 5

- include_tasks: firewall.yml

- name: Create scheduler group
  become: yes
  ansible.builtin.group:
    name: "{{ scheduler_os_group }}"
    state: present

- name: Create scheduler user
  become: true
  ansible.builtin.user:
    name: "{{ scheduler_os_user }}"
    group: "{{ scheduler_os_group }}"
    groups: "{{ (container_command == 'docker') | ternary('docker', '', omit) }}"
    state: "present"

- name: Write Scheduler SystemD unit file
  become: true
  ansible.builtin.template:
    src: "apimon-scheduler.service.j2"
    dest: "{{ scheduler_systemd_unit_path }}"
  notify:
    - Restart scheduler

- name: Create required directories
  become: true
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    state: "directory"
    owner: "{{ scheduler_os_user }}"
    group: "{{ scheduler_os_group }}"
    mode: "{{ item.mode | default(omit) }}"
  loop:
    - {dest: "{{ scheduler_config_dir }}", mode: "0755"}

- name: Write env
  become: true
  ansible.builtin.template:
    src: "env_scheduler"
    dest: "{{ scheduler_env_path }}"
    group: "{{ scheduler_os_group }}"
    owner: "{{ scheduler_os_user }}"
    mode: "0644"
  notify:
    - Restart scheduler

- name: Write logging.conf
  become: true
  ansible.builtin.template:
    src: "logging.conf"
    dest: "{{ scheduler_config_dir }}/logging.conf"
    group: "{{ scheduler_os_group }}"
    owner: "{{ scheduler_os_user }}"
    mode: "0644"
  notify:
    - Restart scheduler

- name: Write scheduler config
  become: true
  ansible.builtin.copy:
    content: "{{ scheduler_config | to_nice_yaml(indent=2, width=79) }}"
    dest: "{{ scheduler_config_dir }}/{{ scheduler_config_file_name }}"
    group: "{{ scheduler_os_group }}"
    owner: "{{ scheduler_os_user }}"
    mode: "0644"
  when:
    - "scheduler_config is defined"
  notify:
    - Restart scheduler

- name: Write scheduler secure config
  become: true
  ansible.builtin.copy:
    content: "{{ scheduler_secure_config | to_nice_yaml(indent=2, width=79) }}"
    dest: "{{ scheduler_config_dir }}/{{ scheduler_secure_config_file_name }}"
    group: "{{ scheduler_os_group }}"
    owner: "{{ scheduler_os_user }}"
    mode: "0644"
  when:
    - "scheduler_secure_config is defined"
  notify:
    - Restart scheduler
