---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: base
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: sdb-redis-cache
      app.kubernetes.io/version: 1.0.0

resources:
  - service.yaml
  - deployment.yaml
  - configmap.yaml
