---
# handlers file for globalmon
- name: Restart globalmon
  become: true
  ansible.builtin.systemd:
    name: "{{ globalmon_systemd_service_name }}"
    enabled: true
    state: "restarted"
    daemon_reload: true
