- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  failed_when: false
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_facts.distribution_major_version == '22'

- name: Configure apt retries
  copy:
    mode: 0444
